---
title: "Cars Analysis"
format: html
editor: visual
---

#### Load in Libraries

```{r}
library(tidyverse)
library(plotly)
```

#### Read in Dataset

```{r}
mtcars <- datasets::mtcars
```

```{r}
?mtcars
```

#### Examining relationship between weight and miles per gallon

```{r}
cars_wt_mpg <- ggplot(data = mtcars, aes(x = mpg, y = wt)) +
  geom_point()
cars_wt_mpg
```

```{r}
ggplotly(cars_wt_mpg)
```

```{r}
mtcars <- mtcars %>%
  tibble::rownames_to_column("model")
```

```{r}
cars_wt_mpg <- ggplot(data = mtcars, aes(x = mpg, y = wt, label = model, color = hp)) +
  geom_point()
cars_wt_mpg
```

```{r}
ggplotly(cars_wt_mpg)
```

```{r}
mtcars_split <- mtcars %>%
  separate(model, into = c("make", "model"), sep = " ", extra = "merge")
```

```{r}
ggplot(data = mtcars_split, aes(x = make, y = mpg, fill = model)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
average_cars_mpg <- mtcars_split %>% 
  group_by(make) %>%
  summarise(avg_mpg = mean(mpg))
```

```{r}
ggplot(data = average_cars_mpg, aes(y = make, x = avg_mpg)) +
  geom_bar(stat = "identity")
```

```{r}
ggplot(data = average_cars_mpg, aes(y = reorder(make,avg_mpg), x = avg_mpg)) +
  geom_bar(stat = "identity")
```
